[[Chafa]]
arch = "aarch64"
git-tree-sha1 = "618e64c2218801ff5c9cb2689b43eb8badcef994"
libc = "glibc"
os = "linux"

    [[Chafa.download]]
    sha256 = "7150c32834c91c76c5f49b1e1a6485bbe6d9d38509f4395592470f59f8354c65"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.aarch64-linux-gnu.tar.gz"
[[Chafa]]
arch = "aarch64"
git-tree-sha1 = "679a7d4ad2f7752601507103413642e20729ed5a"
libc = "musl"
os = "linux"

    [[Chafa.download]]
    sha256 = "27633ddaf7f4584dfbf9f7b667bd01b8fafea75a99a7c00c03aa1de4911ce65f"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.aarch64-linux-musl.tar.gz"
[[Chafa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d86953fa2e9602c5effef4293b4166471e866ef"
libc = "glibc"
os = "linux"

    [[Chafa.download]]
    sha256 = "7762b905c1c391b7fee07f74f9078f75ac2bb26c85b5cd2c2b64b8d41edf4139"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.armv7l-linux-gnueabihf.tar.gz"
[[Chafa]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e30a36907be392aa47325a31c18351c69144bc17"
libc = "musl"
os = "linux"

    [[Chafa.download]]
    sha256 = "59c491bf01e642eb585ae9bd756fbb37573d59888125d3fdce4e5fb3627879fe"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.armv7l-linux-musleabihf.tar.gz"
[[Chafa]]
arch = "i686"
git-tree-sha1 = "7eba6f9726760038f1cff8be209cd9753845c138"
libc = "glibc"
os = "linux"

    [[Chafa.download]]
    sha256 = "51577f2a1cda5aba36021d4da7f70f21c51ad0cb3ae516a6e1bb9c76a367e502"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.i686-linux-gnu.tar.gz"
[[Chafa]]
arch = "i686"
git-tree-sha1 = "9d253a5f1c56155aa27623cf0cf46c7ce88473ab"
libc = "musl"
os = "linux"

    [[Chafa.download]]
    sha256 = "d682edfaea3f29a736e8214abf6ee2807b1f2e7043500793fb33d168b99e47d2"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.i686-linux-musl.tar.gz"
[[Chafa]]
arch = "powerpc64le"
git-tree-sha1 = "f08bbe1b58ec909fa61d2ce46fca1d37e7b165e9"
libc = "glibc"
os = "linux"

    [[Chafa.download]]
    sha256 = "922ffd28d25563c76f93839eec95b2694be52f7481d7a2fed2daccc100f52dc4"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.powerpc64le-linux-gnu.tar.gz"
[[Chafa]]
arch = "x86_64"
git-tree-sha1 = "af63bdb06bfa48fc25d26065d7684d13a7f5285f"
os = "macos"

    [[Chafa.download]]
    sha256 = "a6c752922e61f504798ff8cc22f2f2ee1a0bdd4d3473e220030421a4ec030ff5"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.x86_64-apple-darwin.tar.gz"
[[Chafa]]
arch = "x86_64"
git-tree-sha1 = "a04691c9c5fe399a1c258d5e4c729d3c5b4f5078"
libc = "glibc"
os = "linux"

    [[Chafa.download]]
    sha256 = "6d12c0bd10d541e2b04de9f1f0608b0e0dcd16f8f847b275510c41113af2f896"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.x86_64-linux-gnu.tar.gz"
[[Chafa]]
arch = "x86_64"
git-tree-sha1 = "1f726891ba7a0f7148dbcc2d05017331cae80c4a"
libc = "musl"
os = "linux"

    [[Chafa.download]]
    sha256 = "00cf47e4ebed60b24732ab70b4df6b387882146e753bae4834a863c452f44722"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.x86_64-linux-musl.tar.gz"
[[Chafa]]
arch = "x86_64"
git-tree-sha1 = "5720f59dda9e953fd079010b18887baf38952bee"
os = "freebsd"

    [[Chafa.download]]
    sha256 = "fdaa8176e891954e0a2dd838341a53ee46d54049d897829e2d9dec4d79ce85b1"
    url = "https://github.com/JuliaBinaryWrappers/Chafa_jll.jl/releases/download/Chafa-v1.8.0+0/Chafa.v1.8.0.x86_64-unknown-freebsd.tar.gz"
